<a href="https://colab.research.google.com/github/HuseyinKutlukkaya/Breast-Cancer-Classification/blob/main/BreastCancerClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing the libraries

In [93]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the dataset


In [94]:
dataset=pd.read_csv('breast-cancer-wisconsin.data', header=None)
dataset=dataset.replace('?',np.nan)
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
y=y.reshape(len(y),1)

In [95]:
print(X)

[[1000025 5 1 ... 3 1 1]
 [1002945 5 4 ... 3 2 1]
 [1015425 3 1 ... 3 1 1]
 ...
 [888820 5 10 ... 8 10 2]
 [897471 4 8 ... 10 6 1]
 [897471 4 8 ... 10 4 1]]


In [96]:
print(y)

[[2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [2]
 [2]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [2]
 [4]
 [2]
 [2]
 [2]
 [4]
 [4]
 [2]
 [4]
 [4]
 [4]
 [2]
 [4]
 [4]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]


# Fixing missing data

In [97]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X[:, 0:10])
X[:, 0:10]=imputer.transform(X[:, 0:10])

#Splitting data into training set and test set

In [98]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test= train_test_split(X ,y , test_size= 0.2 , random_state=0)

#Future Scaling

In [99]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training



In [100]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors= 5 ,metric ='minkowski')
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

#Predicting

In [101]:
y_prediction= classifier.predict(X_test)
print(np.concatenate((y_prediction.reshape(len(y_prediction),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [4 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 4]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]]


#Metrics

In [102]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm= confusion_matrix(y_test ,y_prediction)
print(cm)
accuracy_score(y_test,y_prediction)

[[83  2]
 [ 3 52]]


0.9642857142857143